# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets

class Ui_Home(object):
    def setupUi(self, Home):
        Home.setObjectName("Home")
        Home.resize(654, 410)
        self.label = QtWidgets.QLabel(Home)
        self.label.setGeometry(QtCore.QRect(140, 20, 371, 41))
        self.label.setStyleSheet("font: 18pt \"造字工房尚黑 G0v1 粗体\";")
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(Home)
        self.groupBox.setGeometry(QtCore.QRect(180, 130, 451, 241))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox)
        self.textBrowser.setGeometry(QtCore.QRect(0, 0, 451, 241))
        self.textBrowser.setObjectName("textBrowser")
        self.groupBox_2 = QtWidgets.QGroupBox(Home)
        self.groupBox_2.setGeometry(QtCore.QRect(180, 80, 451, 41))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_path = QtWidgets.QLabel(self.groupBox_2)
        self.label_path.setGeometry(QtCore.QRect(10, 10, 54, 21))
        self.label_path.setObjectName("label_path")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit.setGeometry(QtCore.QRect(60, 11, 341, 19))
        self.lineEdit.setObjectName("lineEdit")
        self.toolButton = QtWidgets.QToolButton(self.groupBox_2)
        self.toolButton.setGeometry(QtCore.QRect(400, 10, 37, 21))
        self.toolButton.setObjectName("toolButton")
        self.label_1 = QtWidgets.QLabel(Home)
        self.label_1.setGeometry(QtCore.QRect(20, 130, 71, 16))
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(Home)
        self.label_2.setGeometry(QtCore.QRect(20, 150, 71, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Home)
        self.label_3.setGeometry(QtCore.QRect(20, 170, 71, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Home)
        self.label_4.setGeometry(QtCore.QRect(20, 190, 71, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Home)
        self.label_5.setGeometry(QtCore.QRect(20, 210, 71, 16))
        self.label_5.setObjectName("label_5")
        self.label_8 = QtWidgets.QLabel(Home)
        self.label_8.setGeometry(QtCore.QRect(20, 270, 71, 16))
        self.label_8.setObjectName("label_8")
        self.label_6 = QtWidgets.QLabel(Home)
        self.label_6.setGeometry(QtCore.QRect(31, 230, 61, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Home)
        self.label_7.setGeometry(QtCore.QRect(31, 250, 61, 16))
        self.label_7.setObjectName("label_7")
        self.lineEdit_1 = QtWidgets.QLineEdit(Home)
        self.lineEdit_1.setGeometry(QtCore.QRect(100, 130, 61, 16))
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.lineEdit_2 = QtWidgets.QLineEdit(Home)
        self.lineEdit_2.setGeometry(QtCore.QRect(100, 150, 61, 16))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Home)
        self.lineEdit_3.setGeometry(QtCore.QRect(100, 170, 61, 16))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(Home)
        self.lineEdit_4.setGeometry(QtCore.QRect(100, 190, 61, 16))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(Home)
        self.lineEdit_5.setGeometry(QtCore.QRect(100, 210, 61, 16))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(Home)
        self.lineEdit_6.setGeometry(QtCore.QRect(100, 230, 61, 16))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(Home)
        self.lineEdit_7.setGeometry(QtCore.QRect(100, 250, 61, 16))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(Home)
        self.lineEdit_8.setGeometry(QtCore.QRect(100, 270, 61, 16))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.pushButton_suspend = QtWidgets.QPushButton(Home)
        self.pushButton_suspend.setGeometry(QtCore.QRect(100, 370, 71, 23))
        self.pushButton_suspend.setObjectName("pushButton_Check")
        self.pushButton_Start = QtWidgets.QPushButton(Home)
        self.pushButton_Start.setGeometry(QtCore.QRect(10, 370, 71, 23))
        self.pushButton_Start.setObjectName("pushButton_Start")
        self.label_10 = QtWidgets.QLabel(Home)
        self.label_10.setGeometry(QtCore.QRect(500, 379, 141, 31))
        self.label_10.setObjectName("label_10")
        self.list = QtWidgets.QRadioButton(Home)
        self.list.setGeometry(QtCore.QRect(20, 320, 71, 20))
        self.list.setObjectName("checkBox")
        self.error = QtWidgets.QRadioButton(Home)
        self.error.setGeometry(QtCore.QRect(100, 320, 71, 20))
        self.error.setObjectName("checkBox_2")
        self.person = QtWidgets.QRadioButton(Home)
        self.person.setGeometry(QtCore.QRect(20, 340, 71, 20))
        self.person.setObjectName("checkBox_3")
        self.five = QtWidgets.QRadioButton(Home)
        self.five.setGeometry(QtCore.QRect(100, 340, 71, 20))
        self.five.setObjectName("checkBox_3")
        self.label_9 = QtWidgets.QLabel(Home)
        self.label_9.setGeometry(QtCore.QRect(10, 300, 71, 20))
        self.label_9.setObjectName("label_9")
        self.label_11 = QtWidgets.QLabel(Home)
        self.label_11.setGeometry(QtCore.QRect(10, 110, 54, 12))
        self.label_11.setObjectName("label_11")

        self.retranslateUi(Home)
        QtCore.QMetaObject.connectSlotsByName(Home)

    def retranslateUi(self, Home):
        _translate = QtCore.QCoreApplication.translate
        Home.setFixedSize(Home.width(), Home.height())  # 禁止窗口伸缩
        Home.setWindowTitle(_translate("Home", "CEIBAⅡ自动化剪辑辅助工具V4.0"))
        self.label.setText(_translate("Home", "CEIBAⅡ自动化剪辑辅助工具V4.0"))
        self.textBrowser.setHtml(_translate("Home", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_path.setText(_translate("Home", "工作目录"))
        self.toolButton.setText(_translate("Home", "..."))
        self.label_1.setText(_translate("Home", "视频剪辑坐标"))
        self.label_2.setText(_translate("Home", "确定按钮坐标"))
        self.label_3.setText(_translate("Home", "保存路径坐标"))
        self.label_4.setText(_translate("Home", "开始时间坐标"))
        self.label_5.setText(_translate("Home", "结束时间坐标"))
        self.label_8.setText(_translate("Home", "剪辑开始坐标"))
        self.label_6.setText(_translate("Home", " 转AVI坐标"))
        self.label_7.setText(_translate("Home", "新任务坐标"))
        self.pushButton_suspend.setText(_translate("Home", "暂停剪辑"))
        self.pushButton_Start.setText(_translate("Home", "开始剪辑"))
        self.label_10.setText(_translate("Home", "By JonSon  2018.08.11"))
        self.list.setText(_translate("Home", "list"))
        self.error.setText(_translate("Home", "error"))
        self.person.setText(_translate("Home", "行人检测"))
        self.five.setText(_translate("Home", "小五专用"))
        self.label_9.setText(_translate("Home", "选择视频类型"))
        self.label_11.setText(_translate("Home", "输入坐标"))

